config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'main/trail'
  get '/login' => 'session#new'
  post '/login' =>  'session#create'
  delete '/logout' => 'session#destroy'
  

  get 'users/new', as: :sign_up
  resources :users 
  resources :trails
  
  

end

app/models/trail.rb
class Trail < ActiveRecord::Base
  has_many :trail_users, dependent: :destroy
  has_many :users, :through => :trail_users
	# validates_uniqueness_of :url
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, only: [:show, :edit, :update, :destroy]
#respond_to :html, :xml, :json, :js
  # GET /trails
  # GET /trails.json
  def index
    @trails = Trail.all
  end

  # GET /trails/1
  # GET /trails/1.json
  def show
    @trail = Trail.find(params[:id])
    @lat = @trail.lat
    @lon = @trail.lon
    gon.lat = @lat
    gon.lon = @lon
    gon.user_lat = current_user.latitude
    gon.user_lon = current_user.longitude

      #respond_with(@trail) do |format|
       # format.js {render :json => @trail, :callback => params[:callback]}
      #end
  end

  # GET /trails/new
  def new
    @trail = Trail.new
    @trail.url = params[:url]
    @trail.name = params[:title]
    @trail.lon = params[:lon]
    @trail.lat = params[:lat]
  end

  # GET /trails/1/edit
  def edit
  end

  # POST /trails
  # POST /trails.json
  def create
    @trail = Trail.new(trail_params)

    respond_to do |format|
      if @trail.save
        format.html { redirect_to @trail, notice: 'Trail was successfully created.' }
        format.json { render :show, status: :created, location: @trail }
      else
        format.html { render :new }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trails/1
  # PATCH/PUT /trails/1.json
  def update
    respond_to do |format|
      if @trail.update(trail_params)
        format.html { redirect_to @trail, notice: 'Trail was successfully updated.' }
        format.json { render :show, status: :ok, location: @trail }
      else
        format.html { render :edit }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trails/1
  # DELETE /trails/1.json
  def destroy
    @trail.destroy
    respond_to do |format|
      format.html { redirect_to trails_url, notice: 'Trail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trail
      @trail = Trail.find(params[:id])
    end
    

        def trail_params
        params.require(:trail).permit(:name, :url, :lat, :lon )
        end
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/trails/_form.html.erb
<%= form_for(@trail) do |f| %>
  <% if @trail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trail.errors.count, "error") %> prohibited this trail from being saved:</h2>

      <ul>
      <% @trail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :latitude%><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :longitude%><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trails/edit.html.erb
<h1>Editing Trail</h1>

<%= render 'form' %>

<%= link_to 'Show', @trail %> |
<%= link_to 'Back', trails_path %>

app/views/trails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trails.each do |trail| %>
      <tr>
        <td><%= trail.name %></td>
        <td><%= trail.url %></td>
        <td><%= link_to 'Show', trail %></td>
        <td><%= link_to 'Edit', edit_trail_path(trail) %></td>
        <td><%= link_to 'Destroy', trail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trail', new_trail_path %>

app/views/trails/new.html.erb
<div class="container">
<h1>New Trail</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>
</div>

app/views/trails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trail.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @trail.url %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @trail.lat %>
</p>
<p>
  <strong>Lon:</strong>
  <%= @trail.lon %>
</p>

<%= link_to 'Home', root_path %> |
<%= link_to 'Edit', edit_trail_path(@trail) %> |
<%= link_to 'Back', trails_path %>


<%= javascript_include_tag "http://www.mapquestapi.com/sdk/js/v7.2.s/mqa.toolkit.js?key=Fmjtd%7Cluu8290ynq%2Cbn%3Do5-9470h6" %>
<%= javascript_include_tag 'directions' %>

<h1>Driving Directions</h1>

<div id="map" style="width:1000px; height:400px;"></div>